# Generated by Django 5.0.7 on 2024-08-02 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("capacity", models.IntegerField()),
                ("chairs", models.IntegerField()),
                ("speakers", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("people", models.IntegerField()),
                ("activity", models.CharField(max_length=100)),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel_app.hall"
                    ),
                ),
            ],
        ),
    ]
